name: Example Website
author: Kukuruz Authors
permalink: /blog/:year/:month/:day/:name/
url: http://www.example.com

filters:
  .html: [htmlmin, styles, scripts]
  .txt: [exec, fold, "-sw 60"]  # comment this out on Windows

markup:
  markdown_angled_quotes: true

search:
  index: /search/search-index.json
  exclude:
    - 404.html

compress:
  methods:
    - gzip
    - br
  extensions:
    - txt
    - html
    - js
    - css
    - xml
    - json
